export const GET_BOOKING_ITEMS = 'GET_BOOKING_ITEMS';
export const UPDATE_BOOKING_ITEMS = 'UPDATE_BOOKING_ITEMS';
export const REMOVE_BOOKING_ITEMS = 'REMOVE_BOOKING_ITEMS';
export const REMOVE_BOOKING_ITEM = 'REMOVE_BOOKING_ITEM';
export const ADD_BOOKING_ITEM = 'ADD_BOOKING_ITEM';