export const UPDATE_LOADER_STATUS = 'UPDATE_LOADER_STATUS';
export const UPDATE_LOGGED_IN_USER_DATA = 'UPDATE_LOGGED_IN_USER_DATA';
export const REMOVE_LOGGED_IN_USER_DATA = 'REMOVE_LOGGED_IN_USER_DATA';